version: '3.8'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_USER: shop
      MYSQL_PASSWORD: V3ryS3curePassw0rd
      MYSQL_ROOT_PASSWORD: V3ryS3curePassw0rd
      MYSQL_DATABASE: shop
    command:
      - --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  data: